apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  - issuer.yaml
  - secret.yaml

patches:
  - path: args.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
