apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux
  path: ./kubernetes/apps/snapshot-controller/app
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: true
  targetNamespace: snapshot-controller
