apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opencloud

resources:
  - configmap-opencloud-env.yaml
  - admin-secret.yaml
  - pvc-opencloud-config.yaml
  - pvc-opencloud-data.yaml
  - pvc-opencloud-apps.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
