apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/apps/argocd
    repoURL: https://github.com/prankstr/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
