apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

resources:
  - secret.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    namespace: authentik
    releaseName: authentik
    valuesFile: values.yaml
    version: 2025.4.1
    version: 2025.2.0
    version: 2025.2.1
