apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vikunja

resources:
  - secret.yaml

images:
  - name: vikunja/vikunja
    newTag: 0.24.6

helmCharts:
  # Need to set namespace here as well, otherwise some resources are created in the wrong namespace
  - namespace: vikunja
    name: vikunja
    releaseName: vikunja
    repo: oci://kolaente.dev/vikunja
    includeCRDs: true
    valuesFile: values.yaml
    version: 1.0.0
