apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-arc
  namespace: flux
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux
  path: ./kubernetes/apps/github-arc/app
  prune: true
  wait: true
  targetNamespace: github-arc
