apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-arc

resources:
  - rbac.yaml
  - secret.yaml

helmCharts:
  - namespace: github-arc
    name: gha-runner-scale-set-controller
    releaseName: arc
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    includeCRDs: true
  - namespace: github-arc
    name: gha-runner-scale-set
    releaseName: arc-runner-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    includeCRDs: true
    valuesFile: values.yaml
