apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-arc

resources:
  - rbac.yaml
  - secret.yaml

patches:
  - path: remove-preserveunknownfields.yaml
    target:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      version: v1

helmCharts:
  - namespace: github-arc
    name: gha-runner-scale-set-controller
    releaseName: arc
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    includeCRDs: true
    valuesFile: values-controller.yaml
  - namespace: github-arc
    name: gha-runner-scale-set
    releaseName: arc-runner-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    includeCRDs: true
    valuesFile: values-scale-set.yaml
