githubConfigUrl: https://github.com/prankstr/homelab
githubConfigSecret: github-runner-controller-manager
controllerServiceAccount:
  namespace: github-arc
  name: arc-gha-rs-controller
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi
  kubernetesModeServiceAccount:
    annotations:
template:
  spec:
    securityContext:
      fsGroup: 1001
