apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi

resources:
  - namespace.yaml

images:
  - name: docker.io/democraticcsi/democratic-csi
    newTag: next

helmCharts:
  - name: snapshot-controller
    repo: https://democratic-csi.github.io/charts/
    namespace: democratic-csi
    releaseName: snapshot-controller
    version: 0.3.0
    includeCRDs: true
    valuesFile: values-snapshot-controller.yaml
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    namespace: democratic-csi
    releaseName: nfs
    version: 0.15.0
    valuesFile: values-nfs.yaml
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    namespace: democratic-csi
    releaseName: nfs-encrypted
    version: 0.15.0
    valuesFile: values-nfs-encrypted.yaml
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    namespace: democratic-csi
    releaseName: iscsi
    version: 0.15.0
    valuesFile: values-iscsi.yaml
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    namespace: democratic-csi
    releaseName: iscsi-encrypted
    version: 0.15.0
    valuesFile: values-iscsi-encrypted.yaml
