apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - datasources.yaml
  - alertmanager-config-secret.yaml
  - homeassistant-token-secret.yaml
  - helmrepository.yaml
  - ocirepository.yaml
  - victoria-logs-single-helmrelease.yaml
  - victoria-metrics-agent-helmrelease.yaml
  - victoria-metrics-k8s-stack-helmrelease.yaml
  - victoria-metrics-single-helmrelease.yaml
  - prometheus-operator-crds-helmrelease.yaml
