apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - datasources.yaml
  - alertmanager-config-secret.yaml
  - homeassistant-token-secret.yaml
  - helmrepository.yaml
  - ocirepository.yaml
  - victoria-logs-single-helmrelease.yaml
  - victoria-metrics-agent-helmrelease.yaml
  - victoria-metrics-k8s-stack-helmrelease.yaml
  - victoria-metrics-single-helmrelease.yaml
  - prometheus-operator-crds-helmrelease.yaml

patches:
  - path: server-side-apply-patch.yaml
    target:
      kind: ConfigMap
      name: victoria-metrics-k8s-stack-vmagent
  - path: server-side-apply-patch.yaml
    target:
      kind: ConfigMap
      name: victoria-metrics-k8s-stack-victoriametrics
  - path: server-side-apply-patch.yaml
    target:
      kind: ConfigMap
      name: victoria-metrics-k8s-stack-node-exporter-full
  - path: coredns-patch.yaml
    target:
      kind: Service
      name: victoria-metrics-k8s-stack-coredns
