apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
  labels:
    name: victoria-metrics
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: baseline

