apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: victoria-metrics
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: prometheus-community
  values:
    crds:
      alertmanagerconfigs:
        enabled: false

      alertmanagers:
        enabled: false

      podmonitors:
        enabled: true

      probes:
        enabled: false

      prometheusagents:
        enabled: false

      prometheuses:
        enabled: false

      prometheusrules:
        enabled: true

      scrapeconfigs:
        enabled: false

      servicemonitors:
        enabled: true

      thanosrulers:
        enabled: false
