rbac:
  namespaced: true

server:
  fullnameOverride: victoria-metrics-long-term
  retentionPeriod: 10y
  resources:
    requests:
      memory: "200Mi"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    hosts:
      - name: metrics-lts.{ MY_DOMAIN }
        path: /
        port: http
    tls:
      - secretName: metrics-lts.{ MY_DOMAIN }-cert
        hosts:
          - metrics-lts.{ MY_DOMAIN }
    ingressClassName: nginx
    pathType: Prefix
  extraVolumes:
    - name: homeassistant-token
      secret:
        secretName: homeassistant-token
  extraVolumeMounts:
    - name: homeassistant-token
      mountPath: /homeassistant
  scrape:
    enabled: true
    config:
      scrape_configs:
        - job_name: homeassistant
          static_configs:
            - targets:
                - homeassistant.{ MY_DOMAIN }
          scheme: https
          bearer_token_file: /homeassistant/token
          metrics_path: /api/prometheus
          tls_config:
            insecure_skip_verify: true
        - job_name: husdata-exporter
          static_configs:
            - targets:
                - homeassistant.{ MY_DOMAIN }:9101
