apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

helmCharts:
  - namespace: longhorn-system
    name: longhorn
    releaseName: lonhgorn
    repo: https://charts.longhorn.io
    includeCRDs: true
    valuesFile: values.yaml
    version: 1.10.0
