apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: disabled-nodes
spec:
  nodeSelector:
    kubernetes.io/hostname: talos3
  properties:
    - name: AutoplaceTarget
      value: "no"
