apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: lvmthin-pool
spec:
  nodeAffinity:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - talos1
              - talos2
  storagePools:
    - name: lvmthin
      lvmThinPool:
        volumeGroup: vg1
        thinPool: thin
      source:
        hostDevices:
          - /dev/nvme0n1
