apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: piraeus-snapshots
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
driver: linstor.csi.linbit.com
deletionPolicy: Delete
