apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-arc-controller
spec:
  interval: 10m
  chartRef:
    name: github-runner-scale-set-controller
    kind: OCIRepository
  releaseName: arc
  values:
    flags:
      excludeLabelPropagationPrefixes:
        - "argocd.argoproj.io/instance"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-arc-runner
spec:
  interval: 10m
  chartRef:
    name: github-runner-scale-set
    kind: OCIRepository
  releaseName: arc-runner-set
  values:
    githubConfigUrl: https://github.com/prankstr/homelab
    githubConfigSecret: github-runner-controller-manager
    controllerServiceAccount:
      namespace: github-arc
      name: arc-gha-rs-controller
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
      kubernetesModeServiceAccount:
        annotations:
    template:
      spec:
        securityContext:
          fsGroup: 1001
