apiVersion: v1
data:
  datasource.yaml: |
    - name: victoriametrics
      type: prometheus
      url: http://vmsingle-victoria-metrics-k8s-stack.victoria-metrics.svc:8429/
      access: proxy
      isdefault: true
      jsondata: 
        {}
    - name: VictoriaMetricsLTS
      type: prometheus
      url: http://vmsingle-fillin.victoria-metrics.svc:8429/
      access: proxy
      isDefault: true
      jsonData: 
        {}
kind: ConfigMap
metadata:
  labels:
    app: victoria-metrics-k8s-stack-grafana
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.101.0
    grafana_datasource: "1"
    helm.sh/chart: victoria-metrics-k8s-stack-0.22.1
  name: victoria-metrics-k8s-stack-grafana-ds
  namespace: victoria-metrics
