rbac:
  namespaced: true

remoteWriteUrls:
  - http://vmsingle-victoria-metrics-k8s-stack.victoria-metrics.svc:8429/api/v1/write

service:
  enabled: true

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - name: vmagent-external.{ MY_DOMAIN }
      path: /
      port: http
  tls:
    - secretName: vmagent-external.{ MY_DOMAIN }-cert
      hosts:
        - vmagent-external.{ MY_DOMAIN }
  ingressClassName: nginx
  pathType: Prefix

extraVolumes:
  - name: homeassistant-token
    secret:
      secretName: homeassistant-token
extraVolumeMounts:
  - name: homeassistant-token
    mountPath: /homeassistant

config:
  scrape_configs:
    - job_name: vmagent
      static_configs:
        - targets: ["localhost:8429"]
    - job_name: victoria-metrics-lts
      static_configs:
        - targets: ["victoria-metrics-long-term:8429"]
    - job_name: molntuss-node-exporter
      static_configs:
        - targets:
            - molntuss.{ MY_DOMAIN }:9100
            - molntuss.{ MY_DOMAIN }:9134
    - job_name: truenas-node-exporter
      static_configs:
        - targets:
            - truenas.{ MY_DOMAIN }:9100
            - truenas.{ MY_DOMAIN }:9134
    - job_name: homeassistant
      static_configs:
        - targets:
            - homeassistant.{ MY_DOMAIN }:8123
      scheme: https
      bearer_token_file: /homeassistant/token
      metrics_path: /api/prometheus
      tls_config:
        insecure_skip_verify: true
    - job_name: husdata-exporter
      static_configs:
        - targets:
            - homeassistant.{ MY_DOMAIN }:9101
