apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kasten

resources:
  - rbac.yaml
  - oidc-secret.yaml
  - vmpodscrape.yaml
  - vmscrapeconfig.yaml
  - helmrelease.yaml
  - helmrepository.yaml
#  - policies-and-profiles/backblaze-credentials-secret.yaml
#  - policies-and-profiles/backblaze-location-profile.yaml
  - policies-and-profiles/standard-preset.yaml
  - policies-and-profiles/argocd.yaml
  - policies-and-profiles/authentik.yaml
  - policies-and-profiles/headscale.yaml
  - policies-and-profiles/mealie.yaml
  - policies-and-profiles/victoria-metrics.yaml
  - policies-and-profiles/vikunja.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"

configMapGenerator:
  - files:
      - kasten-dashboard.json
    name: kasten-dashboard
