apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: argocd
  targetNamespace: argocd
  releaseName: argocd
  valuesFrom:
    - kind: ConfigMap
      name: argocd-values
    - kind: Secret
      name: argocd-secrets
      optional: true
    - kind: ConfigMap
      name: argocd-extra-values
      optional: true
