apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argocd
spec:
  interval: 10m
  url: oci://ghcr.io/argoproj/argo-helm/argo-cd
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
  ref:
    tag: 9.1.6
