apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux
  path: ./kubernetes/apps/metallb/app
  prune: true
  wait: true
  targetNamespace: metallb
