apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

resources:
  - grafana-secret.yaml
  - tibber-secret.yaml
  - tibber-datasource.yaml
  - helmrelease.yaml
  - helmrepository.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configMapGenerator:
  - name: heatpump-dashboard
    files:
      - https://raw.githubusercontent.com/prankstr/hassio-husdata-exporter/main/dashboard.json
  - name: ingress-nginx-controller-dashboard
    files:
      - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/grafana/dashboards/nginx.json
  - name: ingress-nginx-request-performance-dashboard
    files:
      - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/grafana/dashboards/request-handling-performance.json
