apiVersion: v1
kind: ConfigMap
metadata:
  name: k10-k10-metering-config
  namespace: k10
data:
  prometheusTargets: |
    - service: auth
      metricsPath: /metrics
      scheme: http
      fqdn: auth-svc.k10.svc
      port: 8000
      application: k10
    - service: bloblifecyclemanager
      metricsPath: /metrics
      scheme: http
      fqdn: crypto-svc.k10.svc
      port: 8001
      application: k10
    - service: catalog
      metricsPath: /metrics
      scheme: http
      fqdn: catalog-svc.k10.svc
      port: 8000
      application: k10
    - service: controllermanager
      metricsPath: /metrics
      scheme: http
      fqdn: controllermanager-svc.k10.svc
      port: 8000
      application: k10
    - service: crypto
      metricsPath: /metrics
      scheme: http
      fqdn: crypto-svc.k10.svc
      port: 8000
      application: k10
    - service: dashboardbff
      metricsPath: /metrics
      scheme: http
      fqdn: dashboardbff-svc.k10.svc
      port: 8000
      application: k10
    - service: events
      metricsPath: /metrics
      scheme: http
      fqdn: state-svc.k10.svc
      port: 8001
      application: k10
    - service: garbagecollector
      metricsPath: /metrics
      scheme: http
      fqdn: crypto-svc.k10.svc
      port: 8002
      application: k10
    - service: jobs
      metricsPath: /metrics
      scheme: http
      fqdn: jobs-svc.k10.svc
      port: 8000
      application: k10
    - service: logging
      metricsPath: /metrics
      scheme: http
      fqdn: logging-svc.k10.svc
      port: 8000
      application: k10
    - service: metering
      metricsPath: /metrics
      scheme: http
      fqdn: metering-svc.k10.svc
      port: 8000
      application: k10
    - service: repositories
      metricsPath: /metrics
      scheme: http
      fqdn: crypto-svc.k10.svc
      port: 8003
      application: k10
    - service: state
      metricsPath: /metrics
      scheme: http
      fqdn: state-svc.k10.svc
      port: 8000
      application: k10
    - service: vbrintegrationapi
      metricsPath: /metrics
      scheme: http
      fqdn: dashboardbff-svc.k10.svc
      port: 8001
      application: k10
    - service: kanister
      metricsPath: /metrics
      scheme: http
      fqdn: kanister-svc.k10.svc
      port: 8000
      application: k10
