apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie

images:
  - name: ghcr.io/mealie-recipes/mealie
    newTag: v1.10.1

resources:
  - ldap-secret.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - pvc.yaml
