---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
metrics:
  - name: talos_version
    query: node_os_info{name="Talos"}
    label: version_id

  - name: kubernetes_version
    query: kubernetes_build_info{service="kubernetes"}
    label: git_version

  - name: renovate_job_time_since_last_successful_minutes
    query: round((now() - kube_cronjob_status_last_successful_time{cronjob="renovate"}) / 60)
    suffix: "m ago"
    colors:
      - { color: "green", min: 0, max: 60 }
      - { color: "orange", min: 61, max: 1440 }
      - { color: "red", min: 1440, max: 99999 }

  - name: cluster_node_count
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    colors:
      - { color: "green", min: 0, max: 9999 }

  - name: cluster_pod_count
    query: sum(kube_pod_status_phase{phase="Running"})
    colors:
      - { color: "green", min: 0, max: 9999 }

  - name: cluster_cpu_usage
    query: round(avg(instance:node_cpu:ratio{job="victoria-metrics-k8s-stack-prometheus-node-exporter"}) * 100, 0.1)
    suffix: "%"
    colors:
      - { color: "green", min: 0, max: 35 }
      - { color: "orange", min: 36, max: 75 }
      - { color: "red", min: 76, max: 9999 }

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes{job="victoria-metrics-k8s-stack-prometheus-node-exporter"} - node_memory_MemAvailable_bytes{job="victoria-metrics-k8s-stack-prometheus-node-exporter"}) / sum(node_memory_MemTotal_bytes{job="victoria-metrics-k8s-stack-prometheus-node-exporter"}) * 100, 0.1)
    suffix: "%"
    colors:
      - { color: green, min: 0, max: 60 }
      - { color: orange, min: 61, max: 75 }
      - { color: red, min: 76, max: 9999 }

  - name: cluster_power_usage
    query: homeassistant_sensor_power_w{entity="sensor.ups_load_watt"}
    suffix: "w"
    colors:
      - { color: "green", min: 0, max: 400 }
      - { color: "orange", min: 401, max: 750 }
      - { color: "red", min: 751, max: 9999 }

  - name: cluster_age_days
    query: round((time() - min(kube_node_created) ) / 86400)
    suffix: "d"
    colors:
      - { color: "green", min: 0, max: 9999 }

  - name: cluster_uptime_days
    query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
    suffix: "d"
    colors:
      - { color: "green", min: 0, max: 180 }
      - { color: "orange", min: 181, max: 360 }
      - { color: "red", min: 361, max: 9999 }
