apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 10m
  chart:
    spec:
      chart: connect
      version: 2.0.5
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
      interval: 1h
  install:
    createNamespace: true
  values:
    operator:
      create: true
