apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux
  path: ./kubernetes/apps/ingress-nginx/app
  prune: true
  wait: true
