apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - vmservicescrape.yaml

helmCharts:
  # Need to set namespace here as well, otherwise some resources are created in the wrong namespace
  - namespace: ingress-nginx
    name: ingress-nginx
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    includeCRDs: true
    valuesFile: values.yaml
    version: 4.11.2
