name: Telegram Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate-bot'
    steps:
      - name: Extract PR Number from Commit Message
        id: extract_pr
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          echo "Commit message: $commit_message"

          if [[ "$commit_message" =~ \#([0-9]+) ]]; then
            pr_number="${BASH_REMATCH[1]}"
            echo "PR number: $pr_number"
          else
            echo "No PR number found in commit message"
            pr_number=""
          fi
          echo "pull_request_number=$pr_number" >> $GITHUB_OUTPUT

      - name: Notify Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            New commit:
            Message: ${{ github.event.head_commit.message }}

            See PR: https://github.com/${{ github.repository }}/pull/${{ steps.extract_pr.outputs.pull_request_number }}
